name: Jest
on:
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      # Install
      - name: Install Dependencies
        run: npm install

      # Build
      - name: Compile
        uses: npm run compile

      # Tests
      - name: Run the tests
        run: npm run test
